== 회원 API (MemberController)
=== 회원가입 성공 API
==== 요청
operation::member-controller-test/join-test1[snippets="http-request,request-fields"]
==== 요청
operation::member-controller-test/join-test1[snippets="http-response,response-fields"]
=== 회원가입 실패 API (이미 존재하는 ID)
==== 요청
operation::member-controller-test/join-test2[snippets="http-request,request-fields"]
==== 요청
operation::member-controller-test/join-test2[snippets="http-response,response-fields"]
=== 회원정보수정 성공 API (이름 변경)
==== 요청
operation::member-controller-test/update-member-name-test1[snippets="http-request,request-fields"]
==== 요청
operation::member-controller-test/update-member-name-test1[snippets="http-response,response-fields"]
=== 회원정보수정 실패 API (이름 변경 시도 / 회원정보를 찾을 수 없음)
==== 요청
operation::member-controller-test/update-member-name-test2[snippets="http-request,request-fields"]
==== 요청
operation::member-controller-test/update-member-name-test2[snippets="http-response,response-fields"]
=== 회원정보수정 성공 API (비밀번호 변경)
==== 요청
operation::member-controller-test/update-member-password-test1[snippets="http-request,request-fields"]
==== 요청
operation::member-controller-test/update-member-password-test1[snippets="http-response,response-fields"]
=== 회원정보수정 실패 API (비밀번호 변경 시도 / 회원정보를 찾을 수 없음)
==== 요청
operation::member-controller-test/update-member-password-test2[snippets="http-request,request-fields"]
==== 요청
operation::member-controller-test/update-member-password-test2[snippets="http-response,response-fields"]
=== 회원정보수정 실패 API (비밀번호 변경 시도 / 비밀번호가 일치하지 않음)
==== 요청
operation::member-controller-test/update-member-password-test3[snippets="http-request,request-fields"]
==== 요청
operation::member-controller-test/update-member-password-test3[snippets="http-response,response-fields"]
=== 회원추가정보 입력 성공 API
==== 요청
operation::member-controller-test/add-member-info-test1[snippets="http-request,request-fields"]
==== 요청
operation::member-controller-test/add-member-info-test1[snippets="http-response,response-fields"]
=== 회원추가정보 입력 실패 API (회원정보를 찾을 수 없음)
==== 요청
operation::member-controller-test/add-member-info-test1[snippets="http-request,request-fields"]
==== 요청
operation::member-controller-test/add-member-info-test1[snippets="http-response,response-fields"]
